name: Test macos script

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - run: ./mac/init.sh
